# Gradients

In [2]:
# imports
import torch
import warnings
import numpy as np

warnings.filterwarnings("ignore", category=FutureWarning)

print(f'torch version is : {torch.__version__}')
print(f'numpy version is : {np.__version__}')

torch version is : 2.0.0+cpu
numpy version is : 1.23.5


In [7]:
torch.manual_seed(10)

## Creating Tensors with Gradients

In [6]:
a = torch.ones((2, 2), requires_grad=True)
print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [8]:
# check if grad is required
a.requires_grad

True

## Second method to create grads which require gradients

In [9]:
# Normal way of creating gradients
a = torch.ones((2, 2))

# Requires gradient
a.requires_grad_()

# Check if requires gradient
a.requires_grad

True

In [10]:
# if not explicitly told, grad is not required as shown below
# Not a variable
no_gradient = torch.ones(2, 2)
no_gradient.requires_grad

False

## Exact Example of Gradiens
$$ y_i = 5(x + 1)^2 $$
$$ \frac{\mathrm d}{\mathrm d x} \big( 5(x + 1)^2 \big) $$

$$ y_i\bigr\rvert_{x_i=1} = 5(1 + 1)^2 = 5(2)^2 = 5(4) = 20 $$

In [13]:
x = torch.ones(2, requires_grad=True)
print(x)

tensor([1., 1.])


In [14]:
y = 5 * (x + 1) ** 2
y

tensor([20., 20.])